version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ATTENDTOEVENT
  - ATTENDTOWORKSHOP
  - autoincrement
  - chilean
  - datasource
  - ekoru
  - KHIPU
  - nestjs
  - postgresql
  - STOREPURCHASE
  - TIKTOK
  - UPCYCLING
  - uuid
  - WEBPAY
  - WHATSAPP
  - zoho
ignoreWords: []
import: []
